# Project

project.fullname = "Corpus der Entscheidungen des Bundesverfassungsgerichts"
project.shortname = "CE-BVerfG"
project.author = "Seán Fobbe"



# License

license.data = "Creative Commons Zero 1.0 Universal"
license.code = "MIT-0"



# Digital Object Identifier (DOI)

doi.data.concept = "10.5281/zenodo.3902658" # checked
doi.data.version = "10.5281/zenodo.5910152" # checked

doi.software.concept = "10.5281/zenodo.4308216" # checked
doi.software.version = "10.5281/zenodo.5910155" # checked

doi.personendaten = "10.5281/zenodo.4568682" # checked
doi.aktenzeichen = "10.5281/zenodo.4569564" # checked


# Debugging

debug.toggle = false   # Ob Debugging aktiv ist; Möglichkeiten sind "true" oder "false"; Der Debugging-Modus reduziert den Such-Umfang auf den in der Variable "debug.scope" angegebenen Umfang Seiten
debug.sample = 10      # Die Anzahl der zufällig ausgewählten Seiten, die im Debugging-Modus berücksichtigt werden sollen (jede Seite enthält idR 10 Entscheidungen). Muss mindestens 10 betragen.



# Annotation

annotate.toggle = true # Wenn dieser Modus aktiviert ist wird  mittels spacyr eine zusätzliche Variante des Datensatzes mit umfangreichen linguistischen Annotationen berechnet. Sehr rechenintensiv!



# Parallelization

cores.max = true  # Ob die maximale Anzahl an logischen Kernen genutzt werden soll; Möglichkeiten sind "true" oder "false"
cores.number = 8   # Die Anzahl Rechtenkerne, die verwendet werden soll; wird nur berücksichtigt falls "cores.max" auf "false" steht


parallel.extractPDF = true
parallel.lingsummarize = true
parallel.spacyparse = false
parallel.multihashes = true



# Download
download.timeout = 600			# Timeout für Downloads



# Quanteda
quanteda.tokens_locale = "de_DE" # Locale in denen Tokens analyisert werden



# Knitr

fig.format = [ "pdf", "png" ] 	# Ausgabe-Format für Diagramme
fig.dpi = 300     	 	# Auflösung für Diagramme
fig.align = "center"    	# Ausrichtung von Diagrammen im Compilation Report



# Frequenztabellen: Ignorierte Variablen
#' **Hinweis:** Diese Variablen werden bei der Erstellung der Frequenztabellen nicht berücksichtigt.

freqtable.ignore = ["text",
		    "eingangsnummer",
		    "datum",
		    "doc_id",
		    "seite",
		    "name",
		    "ecli",
		    "aktenzeichen",
		    "pressemitteilung",
		    "zitiervorschlag",
		    "kurzbeschreibung"]
