[project]

fullname = "Corpus der Entscheidungen des Bundespatentgerichts"
shortname = "CE-BPatG"
author = "Seán Fobbe"



[license]

data = "Creative Commons Zero 1.0 Universal"
code = "GPLv3"



[doi] # Digital Object Identifier (DOI)

data.concept = "10.5281/zenodo.3954850" # do not change
data.version = "10.5281/zenodo.10849977" # checked

software.concept = "10.5281/zenodo.6667305" # do not change
software.version = "10.5281/zenodo.10849980" # checked

personendaten = "10.5281/zenodo.4568682" # checked
aktenzeichen = "10.5281/zenodo.4569564" # checked


[debug]

toggle = false   # Ob Debugging aktiv ist; Möglichkeiten sind "true" oder "false"
pages = 50     # Die Anzahl der zufällig ausgewählten Seiten aus der Datenbank, die im Debugging-Modus berücksichtigt werden sollen (jede Seite enthält idR 30 Entscheidungen).

cleanrun = false # Löscht vor jedem Run alle gespeicherten Zwischen- und Endergebnisse (Hinweis: ist unabhängig von debug.toggle, aber idR für Debugging nützlich)



[cores]

max = true  # Ob die maximale Anzahl an logischen Kernen genutzt werden soll; Möglichkeiten sind "true" oder "false"
number = 8   # Die Anzahl Rechtenkerne, die verwendet werden soll; wird nur berücksichtigt falls "cores.max" auf "false" steht


[parallel]

extractPDF = true
lingsummarize = true
multihashes = true



[download]

timeout = 600			# Timeout für Downloads



[quanteda]

tokens_locale = "de_DE" # Locale in denen Tokens analyisert werden



[fig] # Knitr

format = [ "pdf", "png" ] 	# Ausgabe-Format für Diagramme
dpi = 300     	 	# Auflösung für Diagramme
align = "center"    	# Ausrichtung von Diagrammen im Compilation Report
