---
title: "Testbericht Corpus der Entscheidungen des Bundespatentgerichts (CE-BPatG)"
author: Seán Fobbe
geometry: margin=3cm
papersize: a4
fontsize: 11pt
output:
  pdf_document:
    toc: true
    toc_depth: 3
    number_sections: true
    pandoc_args: --listings
    includes:
      in_header: Preamble_DE.tex
---



```{r, setup, include=FALSE}
knitr::opts_chunk$set(fig.path = file.path("..", "analysis/"),
                      dev = config$fig$format,
                      dpi = config$fig$dpi,
                      fig.align = config$fig$align)

```




```{r}

tar_load(dt.bpatg)
tar_load(files.pdf)
tar_load(files.txt)

```




# Dateigrößen analysieren



## Datensatz in RAM (MB)

```{r}
print(object.size(dt.bpatg),
      standard = "SI",
      humanReadable = TRUE,
      units = "MB")
      
```


## CSV Korpus (MB)
file.size(csvname.full) / 10 ^ 6


## CSV Metadaten (MB)
file.size(csvname.meta) / 10 ^ 6



## PDF-Dateien (MB)

```{r}
pdf.MB <- file.size(files.pdf) / 10^6
sum(pdf.MB)
```


## TXT-Dateien (MB)


```{r}
txt.MB <- file.size(files.txt) / 10^6
sum(txt.MB)
```




\newpage
## Diagramm: Verteilung der Dateigrößen (PDF)



```{r, CE-BPatG_13_Density_Dateigroessen_PDF, fig.height = 6, fig.width = 9}

dt.plot <- data.table(pdf.MB)

ggplot(data = dt.plot,
       aes(x = pdf.MB)) +
    geom_density(fill = "#7e0731") +
    scale_x_log10(breaks = trans_breaks("log10", function(x) 10^x),
                  labels = trans_format("log10", math_format(10^.x)))+
    annotation_logticks(sides = "b")+
    theme_bw() +
    labs(
        title = paste(prefix.figuretitle,
                      "| Verteilung der Dateigrößen (PDF)"),
        caption = caption,
        x = "Dateigröße in MB",
        y = "Dichte"
    )+
    theme(
        text = element_text(size = 14),
        plot.title = element_text(size = 14,
                                  face = "bold"),
        legend.position = "none",
        panel.spacing = unit(0.1, "lines"),
        plot.margin = margin(10, 20, 10, 10)
    )
    
```


\newpage
## Diagramm: Verteilung der Dateigrößen (TXT)



```{r, CE-BPatG_14_Density_Dateigroessen_TXT, fig.height = 6, fig.width = 9}

dt.plot <- data.table(txt.MB)

ggplot(data = dt.plot,
       aes(x = txt.MB)) +
    geom_density(fill = "#7e0731") +
    scale_x_log10(breaks = trans_breaks("log10", function(x) 10^x),
                  labels = trans_format("log10", math_format(10^.x)))+
    annotation_logticks(sides = "b")+
    theme_bw() +
    labs(
        title = paste(prefix.figuretitle,
                      "| Verteilung der Dateigrößen (TXT)"),
        caption = caption,
        x = "Dateigröße in MB",
        y = "Dichte"
    )+
    theme(
        text = element_text(size = 14),
        plot.title = element_text(size = 14,
                                  face = "bold"),
        legend.position = "none",
        panel.spacing = unit(0.1, "lines"),
        plot.margin = margin(10, 20, 10, 10)
    )

```